---
# tasks file for java
- name: apt update
  apt:
    update_cache: true
  become: true

- name: Install latest version of {java-version:}
  ansible.builtin.apt:
    name: {java-version:}
    state: latest

- name: Ensure java is installed
  apt:
    name: java
    state: present
